name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: django_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user -d django_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - ./tmp/data:/var/lib/postgresql/data

    steps:
      - name: Remove tmp/data directory
        run: |
          sudo rm -rf ./tmp/data

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "DEBUG=0" >> .env
          echo "DEV_DB_NAME=django_db" >> .env
          echo "DEV_DB_USER=user" >> .env
          echo "DEV_DB_PASSWORD=password" >> .env
          echo "DEV_DB_HOST=localhost" >> .env
          echo "DEV_DB_PORT=5432" >> .env
          echo "DEV_EMAIL_HOST=smtp.example.com" >> .env
          echo "DEV_EMAIL_PORT=587" >> .env  
          echo "DEV_EMAIL_HOST_USER=username@example.com" >> .env
          echo "DEV_EMAIL_USE_TLS=True" >> .env
          echo "DEV_EMAIL_HOST_PASSWORD=yourpassword" >> .env
          echo "DEV_DEFAULT_FROM_EMAIL=example@gmail.com" >> .env
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Run migrations and test
        run: |
          python manage.py migrate
          python manage.py test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
