name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: django_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user -d django_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - ./tmp/data:/var/lib/postgresql/data

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2

      - name: Set environment variables
        run: |
          echo "DEBUG=0" >> .env
          echo "DATABASE_URL=postgres://user:password@localhost:5432/django_db" >> .env

      - name: Run migrations and test
        run: |
          python manage.py migrate
          python manage.py test
